spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart,/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store,/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                methods: GET
                statuses: NOT_FOUND

        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order,/order/**
          filters:
            - PrefixPath=/api/v1

        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment,/payment/**
          filters:
            - PrefixPath=/api/v1

        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery,/delivery/**
          filters:
            - PrefixPath=/api/v1

server:
  port: 8080