spring:
  application:
    name: shopping-store
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
